name: sjis
version: 0.3.0
description: Converter for SJIS(shift_jis) made for Harmonic
author: Montana Mendy <montana@getprowl.com>
homepage: http://www.montanamendy.com
dependencies: activerecord
unittest: ">=0.9.3 <0.9.4"